name=AKZ
version=5.2
company-website=https://www.voipiran.io
company-en=VOIPIRAN + AKZ
company-fa=ویپ ایران + AKZ
partner-website=https://akzwp.com
partner-website-alt=https://akzwp.ir
partner-en=AKZ
partner-fa=ای کی زد
partner-brand=AKZ
copyright-footer=VOIPIRAN | ویپ ایران + UI Copyright AKZ | akzwp.com | akzwp.ir
